# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(471, 468)
        Form.setMinimumSize(QtCore.QSize(451, 468))
        Form.setMaximumSize(QtCore.QSize(471, 468))
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 451, 101))
        self.groupBox.setMaximumSize(QtCore.QSize(121234, 16777215))
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.esixLinkButton = QtWidgets.QCommandLinkButton(self.groupBox)
        self.esixLinkButton.setGeometry(QtCore.QRect(0, 60, 451, 41))
        self.esixLinkButton.setDescription("")
        self.esixLinkButton.setObjectName("esixLinkButton")
        self.fandomLinkButton_2 = QtWidgets.QCommandLinkButton(self.groupBox)
        self.fandomLinkButton_2.setGeometry(QtCore.QRect(0, 20, 451, 41))
        self.fandomLinkButton_2.setDescription("")
        self.fandomLinkButton_2.setObjectName("fandomLinkButton_2")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 100, 451, 351))
        self.tabWidget.setMinimumSize(QtCore.QSize(451, 341))
        self.tabWidget.setMaximumSize(QtCore.QSize(6454545, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 421, 301))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 401, 261))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 270, 401, 20))
        self.label_5.setStyleSheet("color: rgb(122, 122, 122);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 401, 61))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.downloadfilepathEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.downloadfilepathEdit.setObjectName("downloadfilepathEdit")
        self.horizontalLayout_3.addWidget(self.downloadfilepathEdit)
        self.preview_btn = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.preview_btn.setObjectName("preview_btn")
        self.horizontalLayout_3.addWidget(self.preview_btn)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hint_input = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.hint_input.setObjectName("hint_input")
        self.horizontalLayout.addWidget(self.hint_input)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 80, 401, 191))
        self.groupBox_3.setObjectName("groupBox_3")
        self.ImagewebPreViewer = QtWebEngineWidgets.QWebEngineView(self.groupBox_3)
        self.ImagewebPreViewer.setGeometry(QtCore.QRect(40, 20, 321, 161))
        self.ImagewebPreViewer.setProperty("url", QtCore.QUrl("about:blank"))
        self.ImagewebPreViewer.setObjectName("ImagewebPreViewer")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 421, 20))
        self.label_6.setObjectName("label_6")
        self.download_file = QtWidgets.QPushButton(self.tab_2)
        self.download_file.setGeometry(QtCore.QRect(20, 282, 399, 31))
        self.download_file.setObjectName("download_file")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Changed图片添加器"))
        self.groupBox.setTitle(_translate("Form", "Changed图片常见网站"))
        self.esixLinkButton.setText(_translate("Form", "Changed在e621上的标签"))
        self.fandomLinkButton_2.setText(_translate("Form", "Changed在Fandom上的Wiki"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei UI\'; font-size:10pt; font-weight:696;\">添加任意Changed图片</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei UI\'; font-size:10pt;\">具体的实现原理为：</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei UI\'; font-size:10pt;\">· 将图片文件命名为&quot;你知道吗&quot;的内容之一 </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei UI\'; font-size:10pt;\">· 在显示图片时使用{hint}替代图片路径</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei UI\'; font-size:10pt;\">所以可以通过添加&quot;你知道吗&quot;的条目来将图片添加到播放列表</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei UI\'; font-size:10pt; color:#7a7a7a;\">注：因为文件名不能包含特殊字符(\\ / : ? &quot; &lt; &gt; | )</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei UI\'; font-size:10pt; color:#7a7a7a;\">所以&quot;你知道吗&quot;的内容也不能包含这些字符</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "Designed by HOPE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "原理"))
        self.label_3.setText(_translate("Form", "下载地址"))
        self.preview_btn.setText(_translate("Form", "预览"))
        self.hint_input.setPlaceholderText(_translate("Form", "输入\"你知道吗\"的内容"))
        self.label.setText(_translate("Form", "\"你知道吗\""))
        self.groupBox_3.setTitle(_translate("Form", "图片预览"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ff0000;\">链接必须为以http://或https://开头的网址,部分网址可能无法下载</span></p></body></html>"))
        self.download_file.setText(_translate("Form", "下载并添加"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "添加图片"))
from PyQt5 import QtWebEngineWidgets
